# Generated by Django 6.0.4 on 2026-05-05 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_contactus'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='ContactTeam',
        ),
    ]
