# Generated by Django 6.0.4 on 2026-05-11 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_bloodrequest_contact_alter_contact_phone_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
