# Generated by Django 6.0.4 on 2026-05-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_blooddonation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='blooddonation',
            name='bp',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='hb_level',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='blooddonation',
            name='result',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
