# Generated by Django 6.0.4 on 2026-05-11 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_blooddonation_bp_blooddonation_hb_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('user', 'User')], default='user', max_length=10),
        ),
        migrations.AlterField(
            model_name='blooddonation',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
