# Generated by Django 6.0.4 on 2026-05-11 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_user_role_alter_blooddonation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blooddonation',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
