# Generated by Django 6.0.4 on 2026-05-11 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_blooddonation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donar',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
