# Generated by Django 6.0.4 on 2026-05-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_donar_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
