# Generated by Django 6.0.4 on 2026-05-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_bloodrequest_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='email',
        ),
    ]
